name: CI Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Execute
        run: |
        gcc hello.c
        
      - name: Build and Execute
        run: |
        ./a.out
        
        
