name: CI Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Execute
        run: |
        mkdir bin
        cd bin
        mkdir make
        cd make
        cmake ..
        make
        
      - name: Build and Execute
        run: |
        cd build
        ./a.out
        
        
